// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	DeleteOrderByID(ctx context.Context, id int32) (int64, error)
	GetOrderByID(ctx context.Context, id int32) (Order, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
